### ISSUE TITLE
На планшете плашка поиска наезжает на список

### ISSUE THREAD

**Issue by nemelnikov** [Freika/ruby_courses#16]
[вот можно увидеть](https://habrastorage.org/files/f40/9bf/d9e/f409bfd9ef6144fe820ec6639715a38c.png)

**Comment by dimavasilyev** [comment]
аналогично в safari

**Comment by gambala** [comment]
Планшет какой? Или, что важнее - ширина экрана в пикселях какая?

**Comment by dimavasilyev** [comment]
прошу прощения за неточность.
Macbook Air 13, Safari

**Comment by gambala** [comment]
Пока не удается воспроизвести проблему у себя. Знаю, что встречалась также на Macbook Pro 15 в Chrome.

Думаю, проблема кроется в ширине экрана на ретина-устройствах. Например, на Macbook Air 13 штатное разрешение - 1440 px по ширине; в айпаде из первого сообщения оно тоже большое, но на скриншоте сайт выглядит так, будто ширина меньше 992 px. 

Я слышал, что на ретина устройствах ширина в браузере - это ширина дисплея, деленная пополам. Например для Macbook 13 ширина в браузере будет не 1440, а 720 px. Возможно с такой ситуацией конфликтуют скрипты, отвечающие за адаптивный вид панели поиска, из-за чего она в планшетном варианте выглядит как в десктопном.

**Comment by Freika** [comment]
Задеплоено, проблема решена?

**Comment by dimavasilyev** [comment]
Да, всё работает отлично
