### ISSUE TITLE
Возможное n+1 в запросах к БД

### ISSUE THREAD

**Issue by gambala** [Freika/ruby_courses#24]
![photo8060631868616212](https://cloud.githubusercontent.com/assets/2563426/18026599/a1d43200-6c5d-11e6-87d2-1191ea659239.jpg)

Долго грузится страница, учитывая крайне простой контент - возможно из-за `n+1` запросов к базе. Не уверен, но можно проверить через `bullet` и устранить.

**Comment by Freika** [comment]
Спасибо, посмотрю как будет время

**Comment by Freika** [comment]
Исправлено:

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_2684/leimLiVQkTALwd0HoQSyN1pa2kVo0B/Monosnap%2B2016-10-30%2B10-33-29.png?Expires=1477884835&Signature=B7FS0vpz7qjAuT-gP8o-3qoHwiMCiukaZGf6lHueITLQswubOh0pjrO~6t3uEvYLdx5T35DHahvgDXTREz7JaIFZ4WRXoWx1MWQfb~a8grqSde0T1Doue~-IWxNEy5EDodw17m8zFJyYKFGRsmdis-zbHycKU9TsLEB6DTU1tAQgRovEGZR1-qVsDrpnRUE5F~TCAptVUrU6gOtSbqCL-7bySC4lE0zvc99NPQVrHD5354whTNZHePryZmEc~9w7seIb5LO188zt9ahVbeHBgDGCdm4afMdvzqKdoMk8pqu4pckOhZXUgCo3QxlHovgDqbxcqI5HSbGpbWInB0W~cQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
