### ISSUE TITLE
Fix "unsafe_constantize" issue in app/controllers/rater_controller.rb

### ISSUE THREAD

**Issue by Freika** [Freika/ruby_courses#37]
Unsafe reflection method constantize called with parameter value

https://codeclimate.com/github/Freika/ruby_courses/app/controllers/rater_controller.rb#issue_5884cae751d0be000100006e

**Comment by halfling-rram** [comment]
Решением в данном случае будет удаление контроллера.
Потому что это остатки старого кода из этого комита:
https://github.com/Freika/ruby_courses/commit/ceb87ae70ebcca93a21835699bc5b95b7c32f8a3
